name: Submit Review

on:
  pull_request_review:
    types: ["submitted"]

jobs:
  MoveCardToProgress_job:
    name: Move card to progress
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    # Single quotes must be used here https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#literals
    # PRs from forks don't have required token authorization
    if: |
        github.event.pull_request.head.repo.full_name == github.repository
        && github.event.review.author_association != 'NONE'
        && github.event.review.state == 'changes_requested'
    steps:
      - id: secrets
        uses: SonarSource/vault-action-wrapper@v3
        with:
          secrets: |
            development/github/token/{REPO_OWNER_NAME_DASH}-kanban token | kanban_token;
      - uses: sonarsource/gh-action-lt-backlog/MoveCardAfterReview@v1
        with:
          github-token: ${{ fromJSON(steps.secrets.outputs.vault).kanban_token }}
          column-id: "47fc9ee4"     # Kanban "In progress" column
          project-number: 8

  ReviewApproved_job:
    name: Move card to review approved
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: |
        github.event.pull_request.head.repo.full_name == github.repository
        && github.event.review.author_association != 'NONE'
        && github.event.review.state == 'approved'
    steps:
      - id: secrets
        uses: SonarSource/vault-action-wrapper@v3
        with:
          secrets: |
            development/github/token/{REPO_OWNER_NAME_DASH}-kanban token | kanban_token;
      - uses: sonarsource/gh-action-lt-backlog/MoveCardAfterReview@v1
        with:
          github-token: ${{ fromJSON(steps.secrets.outputs.vault).kanban_token }}
          column-id: "dd10adad"     # Kanban "Review approved" column
          project-number: 8
